// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUhI6b8LzTyi_yQnC5wacNuAZN7t3MNE',
    appId: '1:1072217117210:web:daed06567324b9ff4a77a3',
    messagingSenderId: '1072217117210',
    projectId: 'ltuc-student',
    authDomain: 'ltuc-student.firebaseapp.com',
    storageBucket: 'ltuc-student.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PcqxL0EUuQSFPbr86rP2RpitVMxXX1Q',
    appId: '1:1072217117210:android:85dc5675b7ff27f44a77a3',
    messagingSenderId: '1072217117210',
    projectId: 'ltuc-student',
    storageBucket: 'ltuc-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9cWrxMz59aO4RCyCegTpVERUjaAjWls',
    appId: '1:1072217117210:ios:707525dc63a613004a77a3',
    messagingSenderId: '1072217117210',
    projectId: 'ltuc-student',
    storageBucket: 'ltuc-student.appspot.com',
    iosClientId: '1072217117210-fr5oh9gg8smf9statn04htgftjcj3ft4.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9cWrxMz59aO4RCyCegTpVERUjaAjWls',
    appId: '1:1072217117210:ios:707525dc63a613004a77a3',
    messagingSenderId: '1072217117210',
    projectId: 'ltuc-student',
    storageBucket: 'ltuc-student.appspot.com',
    iosClientId: '1072217117210-fr5oh9gg8smf9statn04htgftjcj3ft4.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );
}
